#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Dialogo de confirmacao do regerar, com os numeros do que fica de pe."""
import io
import sys

P = 'src/app/(app)/planner/page.tsx'
s = io.open(P, encoding='utf-8').read()

velho = "        <MapModal />\n        <RoadmapModal />\n        <AddBlockModal />\n"
assert velho in s, 'ancora dos modais'

novo = (
    "        <MapModal />\n"
    "        <RoadmapModal />\n"
    "        <AddBlockModal />\n"
    "\n"
    "        {/* Confirma\u00e7\u00e3o do \"Gerar com IA\" quando j\u00e1 h\u00e1 progresso.\n"
    "            O app diz o que preserva antes de refazer o plano. */}\n"
    "        <AnimatePresence>\n"
    "          {regenConfirm && (\n"
    "            <motion.div\n"
    "              initial={{ opacity: 0 }}\n"
    "              animate={{ opacity: 1 }}\n"
    "              exit={{ opacity: 0 }}\n"
    "              ref={regenDialog.dialogRef}\n"
    "              {...regenDialog.dialogProps}\n"
    "              className=\"fixed inset-0 z-[90] bg-black/60 backdrop-blur-sm flex items-end sm:items-center justify-center p-4\"\n"
    "              onClick={() => setRegenConfirm(null)}\n"
    "            >\n"
    "              <motion.div\n"
    "                initial={{ opacity: 0, scale: 0.95, y: 30 }}\n"
    "                animate={{ opacity: 1, scale: 1, y: 0 }}\n"
    "                exit={{ opacity: 0, scale: 0.95, y: 30 }}\n"
    "                className=\"bg-card-bg rounded-3xl border border-card-border p-6 w-full max-w-md shadow-2xl\"\n"
    "                onClick={(e) => e.stopPropagation()}\n"
    "              >\n"
    "                <div className=\"flex items-center gap-3 mb-5\">\n"
    "                  <div className=\"h-10 w-10 rounded-xl bg-warning/15 border border-warning/20 flex items-center justify-center\">\n"
    "                    <RefreshCw className=\"h-5 w-5 text-warning\" />\n"
    "                  </div>\n"
    "                  <div>\n"
    "                    <h3 className=\"font-heading text-lg font-bold text-text-primary\">\n"
    "                      Refazer o cronograma?\n"
    "                    </h3>\n"
    "                    <p className=\"text-xs text-text-muted\">\n"
    "                      O que j\u00e1 foi estudado continua valendo.\n"
    "                    </p>\n"
    "                  </div>\n"
    "                </div>\n"
    "\n"
    "                <div className=\"space-y-2 mb-6\">\n"
    "                  <div className=\"flex items-center justify-between rounded-xl border border-card-border bg-background-light px-3 py-2.5\">\n"
    "                    <span className=\"text-sm text-text-secondary\">Blocos j\u00e1 estudados</span>\n"
    "                    <span className=\"text-sm font-bold text-text-primary\">\n"
    "                      {regenConfirm.concluidos} \u00b7 {formatHoursDuration(regenConfirm.horasEstudadas / 60)}\n"
    "                    </span>\n"
    "                  </div>\n"
    "                  <div className=\"flex items-center justify-between rounded-xl border border-card-border bg-background-light px-3 py-2.5\">\n"
    "                    <span className=\"text-sm text-text-secondary\">Blocos pendentes a refazer</span>\n"
    "                    <span className=\"text-sm font-bold text-text-primary\">\n"
    "                      {regenConfirm.pendentes}\n"
    "                    </span>\n"
    "                  </div>\n"
    "                </div>\n"
    "\n"
    "                <p className=\"text-xs text-text-muted mb-6\">\n"
    "                  Os {regenConfirm.concluidos} blocos estudados ficam exatamente como est\u00e3o, com as\n"
    "                  horas j\u00e1 contadas. O app remonta s\u00f3 o que ainda est\u00e1 pendente, come\u00e7ando depois\n"
    "                  do que voc\u00ea j\u00e1 fez em cada dia.\n"
    "                </p>\n"
    "\n"
    "                <div className=\"flex gap-2\">\n"
    "                  <Button\n"
    "                    variant=\"secondary\"\n"
    "                    size=\"sm\"\n"
    "                    className=\"flex-1\"\n"
    "                    onClick={() => setRegenConfirm(null)}\n"
    "                  >\n"
    "                    Cancelar\n"
    "                  </Button>\n"
    "                  <Button\n"
    "                    variant=\"primary\"\n"
    "                    size=\"sm\"\n"
    "                    className=\"flex-1\"\n"
    "                    onClick={() => {\n"
    "                      setRegenConfirm(null);\n"
    "                      void gerarCronograma();\n"
    "                    }}\n"
    "                  >\n"
    "                    <RefreshCw className=\"mr-1.5 h-3.5 w-3.5\" />\n"
    "                    Refazer\n"
    "                  </Button>\n"
    "                </div>\n"
    "              </motion.div>\n"
    "            </motion.div>\n"
    "          )}\n"
    "        </AnimatePresence>\n"
)

s = s.replace(velho, novo, 1)
io.open(P, 'w', encoding='utf-8', newline='\n').write(s)
print('ok')
