/**
 * Reordenação das matérias dentro de um dia.
 *
 * A pessoa arrasta um bloco para outra posição e o app recoloca os blocos
 * pendentes daquele dia na nova ordem, mantendo o intervalo obrigatório entre
 * eles. Não existe escolha de horário: os horários saem da janela do dia e do
 * intervalo configurado, sempre.
 *
 * Duas regras que não se negocia:
 *
 *  1. Bloco já estudado (completed), pulado (skipped) ou em andamento
 *     (in-progress) NÃO se move. Eles formam um prefixo intacto no dia, e a
 *     reordenação acontece só no que ainda está pendente — senão arrastar
 *     uma matéria poderia apagar progresso já creditado.
 *
 *  2. O intervalo entre blocos é preservado, e preservado como bloco: a
 *     agenda mostra o ☕ entre as matérias, então remontar o dia sem recriar
 *     os intervalos deixaria a visualização mentindo sobre o plano.
 */

import { generateId } from '@/lib/utils';
import type { BlockStatus, StudyBlock } from '@/types';

/** Status que representam progresso já feito — nunca reordenados. */
const STATUS_PRESERVADO: ReadonlySet<BlockStatus> = new Set<BlockStatus>([
  'completed',
  'skipped',
  'in-progress',
]);

/**
 * True quando o bloco não participa da reordenação: já foi estudado, pulado,
 * está em andamento, ou é um intervalo (que é consequência, não escolha).
 */
export function isPreservado(block: StudyBlock): boolean {
  return block.isBreak ? true : STATUS_PRESERVADO.has(block.status);
}

/** Separa o dia em prefixo intacto e cauda pendente. Intervalos ficam fora. */
export function splitDay(dayBlocks: StudyBlock[]): {
  preservados: StudyBlock[];
  pendentes: StudyBlock[];
} {
  const ordenados = [...dayBlocks].sort((a, b) => a.startTime.localeCompare(b.startTime));
  const preservados: StudyBlock[] = [];
  const pendentes: StudyBlock[] = [];
  let aindaPreservando = true;

  for (const block of ordenados) {
    if (block.isBreak) continue;
    if (aindaPreservando && STATUS_PRESERVADO.has(block.status)) {
      preservados.push(block);
    } else {
      // A partir do primeiro pendente, tudo o que vem depois é pendente:
      // não faz sentido ter bloco estudado depois de bloco por fazer.
      aindaPreservando = false;
      pendentes.push(block);
    }
  }

  return { preservados, pendentes };
}

export interface ReorderParams {
  /** Todos os blocos do dia, na ordem em que estão na tela. */
  dayBlocks: StudyBlock[];
  /** Índice de origem, contando só os blocos pendentes. */
  fromIndex: number;
  /** Índice de destino, contando só os blocos pendentes. */
  toIndex: number;
  /** Intervalo obrigatório entre blocos, em minutos. */
  breakMinutes: number;
  /** Início da janela do dia ("08:00"), usado como horário de partida. */
  windowStart: string;
}

export interface ReorderResult {
  /** O dia inteiro, remontado: prefixo preservado + pendentes + intervalos. */
  blocks: StudyBlock[];
  /** Quantos blocos pendentes foram remontados. */
  movidos: number;
  /** Quantos blocos ficaram intactos por já terem sido estudados. */
  preservados: number;
  /** Motivo quando nada foi feito. */
  reason?: string;
}

const toMinutes = (hhmm: string): number => {
  const [h, m] = hhmm.split(':').map(Number);
  return (h || 0) * 60 + (m || 0);
};

const toTime = (mins: number): string =>
  `${String(Math.floor(mins / 60)).padStart(2, '0')}:${String(mins % 60).padStart(2, '0')}`;

/** Cria um bloco de intervalo no mesmo formato que o motor de cronograma. */
function makeBreak(date: Date, start: number, minutes: number, userId: string): StudyBlock {
  return {
    id: generateId(),
    userId,
    subjectId: 'break',
    date,
    startTime: toTime(start),
    endTime: toTime(start + minutes),
    durationMinutes: minutes,
    status: 'scheduled',
    isBreak: true,
    isAutoGenerated: true,
  } as StudyBlock;
}

/**
 * Recoloca os blocos pendentes de um dia na ordem pedida e remonta os
 * horários a partir do fim do prefixo preservado, recriando os intervalos.
 */
export function reorderDayBlocks(params: ReorderParams): ReorderResult {
  const { dayBlocks, fromIndex, toIndex, breakMinutes, windowStart } = params;

  const { preservados, pendentes } = splitDay(dayBlocks);

  if (pendentes.length === 0) {
    return {
      blocks: dayBlocks,
      movidos: 0,
      preservados: preservados.length,
      reason: 'Este dia não tem bloco pendente para reordenar.',
    };
  }

  if (
    !Number.isInteger(fromIndex) ||
    !Number.isInteger(toIndex) ||
    fromIndex < 0 ||
    toIndex < 0 ||
    fromIndex >= pendentes.length ||
    toIndex >= pendentes.length
  ) {
    return {
      blocks: dayBlocks,
      movidos: 0,
      preservados: preservados.length,
      reason: 'Posição inválida.',
    };
  }

  // Move o bloco dentro da lista de pendentes.
  const novaOrdem = [...pendentes];
  const [movido] = novaOrdem.splice(fromIndex, 1);
  novaOrdem.splice(toIndex, 0, movido);

  // O relógio começa na janela do dia; se já houve progresso, começa depois
  // do último bloco preservado, para não remarcar por cima do que foi feito.
  const userId = movido.userId || 'user1';
  const date = movido.date;
  const inicioJanela = toMinutes(windowStart);
  let cursor =
    preservados.length > 0
      ? toMinutes(preservados[preservados.length - 1].endTime) + breakMinutes
      : inicioJanela;
  if (preservados.length === 0) {
    cursor = Math.max(cursor, inicioJanela);
  }

  const remontados: StudyBlock[] = [];

  // Intervalo entre o prefixo preservado e o primeiro bloco remontado. Sem
  // ele a agenda mostraria duas matérias encostadas, quebrando a regra do plano.
  if (preservados.length > 0 && breakMinutes > 0) {
    const inicioIntervalo = toMinutes(preservados[preservados.length - 1].endTime);
    remontados.push(makeBreak(date, inicioIntervalo, breakMinutes, userId));
  }

  novaOrdem.forEach((block, index) => {
    const start = cursor;
    const end = start + block.durationMinutes;
    cursor = end;

    remontados.push({ ...block, startTime: toTime(start), endTime: toTime(end) });

    // Intervalo depois de cada bloco, menos depois do último.
    if (index < novaOrdem.length - 1 && breakMinutes > 0) {
      remontados.push(makeBreak(date, cursor, breakMinutes, userId));
      cursor += breakMinutes;
    }
  });

  return {
    blocks: [...preservados, ...remontados],
    movidos: novaOrdem.length,
    preservados: preservados.length,
  };
}
