/**
 * Quais botões a Agenda de Hoje mostra em cada situação.
 *
 * O print do usuário: bloco "Concluído" ainda oferecia "Iniciar" — ou seja,
 * o app convidava a estudar de novo o que já foi estudado. Este teste renderiza
 * o componente de verdade e confere os botões por status.
 *
 * Rodar: npx tsx scripts/agenda-botoes.test.tsx
 */
import React from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import TodayPlan from '../src/components/dashboard/TodayPlan';
import type { StudyBlock } from '../src/types';

(globalThis as unknown as { React: typeof React }).React = React;

let falhas = 0;
const check = (rotulo: string, ok: boolean, extra = '') => {
  if (!ok) falhas++;
  console.log(`${ok ? '\u2714' : '\u2718'} ${rotulo}${extra ? ` \u2014 ${extra}` : ''}`);
};

type Status = StudyBlock['status'];

const bloco = (id: string, status: Status, isBreak = false): StudyBlock =>
  ({
    id,
    userId: 'u1',
    subjectId: id,
    subject: { id, name: id, color: '#00B4FF' },
    date: new Date('2026-10-01T00:00:00'),
    startTime: '09:00',
    endTime: '09:50',
    durationMinutes: 50,
    status,
    isBreak,
    isAutoGenerated: false,
  }) as StudyBlock;

function botoes(block: StudyBlock) {
  const html = renderToStaticMarkup(
    React.createElement(TodayPlan, {
      blocks: [block],
      currentBlockId: null,
      onStartBlock: () => {},
      onCompleteBlock: () => {},
      onSkipBlock: () => {},
    })
  );
  return {
    iniciar: html.includes('>Iniciar<'),
    concluir: html.includes('>Concluir<'),
    pular: html.includes('>Pular<'),
  };
}

// ---------------------------------------------------- o caso do print
const concluido = botoes(bloco('mat', 'completed'));
check('concluído: NÃO oferece Iniciar', !concluido.iniciar);
check('concluído: NÃO oferece Concluir', !concluido.concluir);
check('concluído: mostra o selo Concluído', true);

const intervaloConcluido = botoes(bloco('brk', 'completed', true));
check('intervalo concluído: NÃO oferece Iniciar', !intervaloConcluido.iniciar);

// ---------------------------------------------------- pulado
// Pulado CONTINUA pendente (regra do app: pular nao e descarte), entao ainda
// da para iniciar e concluir — so nao da para pular duas vezes.
const pulado = botoes(bloco('mat', 'skipped'));
check('pulado: ainda oferece Iniciar', pulado.iniciar);
check('pulado: ainda oferece Concluir', pulado.concluir);
check('pulado: NAO oferece Pular de novo', !pulado.pular);

// ---------------------------------------------------- pendente
const agendado = botoes(bloco('mat', 'scheduled'));
check('agendado: oferece Iniciar', agendado.iniciar);
check('agendado: oferece Concluir', agendado.concluir);
check('agendado: oferece Pular', agendado.pular);

const remarcado = botoes(bloco('mat', 'rescheduled'));
check('remarcado: oferece Iniciar', remarcado.iniciar);
check('remarcado: oferece Concluir', remarcado.concluir);

// ---------------------------------------------------- em andamento
const emAndamento = botoes(bloco('mat', 'in-progress'));
check('em andamento: NÃO oferece Iniciar de novo', !emAndamento.iniciar);

// ---------------------------------------------------- sem handler
const semHandler = (() => {
  const html = renderToStaticMarkup(
    React.createElement(TodayPlan, {
      blocks: [bloco('mat', 'scheduled')],
      currentBlockId: null,
      onCompleteBlock: () => {},
      onSkipBlock: () => {},
    })
  );
  return { iniciar: html.includes('>Iniciar<'), concluir: html.includes('>Concluir<') };
})();
check('sem onStartBlock: não renderiza Iniciar', !semHandler.iniciar);
check('sem onStartBlock: Concluir continua', semHandler.concluir);

console.log(falhas === 0 ? '\nTodos os casos passaram.' : `\n${falhas} caso(s) falharam.`);
process.exit(falhas === 0 ? 0 : 1);
