import assert from 'node:assert';
import { autoRescheduleBacklog } from '../src/services/backlogRescheduler';
import type { StudyBlock, Subject } from '../src/types';

const toDateKey = (date: Date) =>
  `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(
    date.getDate()
  ).padStart(2, '0')}`;

const makeSubject = (id: string, priority: number, difficulty: number, pesoNoExame: number): Subject => ({
  id,
  userId: 'user-1',
  name: `Subject ${id}`,
  color: '#00B4FF',
  icon: 'book',
  area: 'geral',
  priority,
  difficulty,
  pesoNoExame,
  targetHours: 10,
  completedHours: 0,
  totalHours: 0,
  sessionsCount: 0,
  averageScore: 0,
  isActive: true,
  createdAt: new Date('2026-01-01T00:00:00'),
  updatedAt: new Date('2026-01-01T00:00:00'),
});

const makeBlock = (params: {
  id: string;
  date: Date;
  startTime: string;
  durationMinutes: number;
  subject: Subject;
  status?: StudyBlock['status'];
  type?: StudyBlock['type'];
  rescheduleCount?: number;
}): StudyBlock => {
  const [startHour, startMinute] = params.startTime.split(':').map(Number);
  const end = new Date(params.date);
  end.setHours(startHour, startMinute + params.durationMinutes, 0, 0);
  const endTime = `${String(end.getHours()).padStart(2, '0')}:${String(end.getMinutes()).padStart(2, '0')}`;

  return {
    id: params.id,
    userId: 'user-1',
    subjectId: params.subject.id,
    subject: params.subject,
    date: new Date(params.date),
    startTime: params.startTime,
    endTime,
    durationMinutes: params.durationMinutes,
    status: params.status ?? 'scheduled',
    isBreak: false,
    isAutoGenerated: true,
    type: params.type ?? 'AULA',
    description: undefined,
    sequenceIndex: undefined,
    relatedSubjectId: undefined,
    originalDate: new Date(params.date),
    completedAt: undefined,
    rescheduleCount: params.rescheduleCount ?? 0,
    createdAt: new Date('2026-01-01T00:00:00'),
    updatedAt: new Date('2026-01-01T00:00:00'),
  };
};

(() => {
  const today = new Date('2026-03-09T00:00:00');
  const yesterday = new Date('2026-03-08T00:00:00');
  const twoDaysAgo = new Date('2026-03-07T00:00:00');
  const tomorrow = new Date('2026-03-10T00:00:00');

  const subjHeavy = makeSubject('heavy', 10, 8, 5);
  const subjMedium = makeSubject('medium', 7, 6, 3);

  const overdueReview = makeBlock({
    id: 'overdue-review',
    date: yesterday,
    startTime: '09:00',
    durationMinutes: 50,
    subject: subjHeavy,
    status: 'scheduled',
    type: 'REVISAO',
  });
  const overdueLesson = makeBlock({
    id: 'overdue-lesson',
    date: twoDaysAgo,
    startTime: '10:00',
    durationMinutes: 50,
    subject: subjMedium,
    status: 'scheduled',
    type: 'AULA',
  });
  const todayPlannedA = makeBlock({
    id: 'today-a',
    date: today,
    startTime: '09:00',
    durationMinutes: 50,
    subject: subjMedium,
    status: 'scheduled',
    type: 'AULA',
  });
  const todayPlannedB = makeBlock({
    id: 'today-b',
    date: today,
    startTime: '10:00',
    durationMinutes: 50,
    subject: subjHeavy,
    status: 'scheduled',
    type: 'EXERCICIOS',
  });

  const capacityMap = {
    [toDateKey(today)]: 180,
    [toDateKey(tomorrow)]: 180,
  };

  const result = autoRescheduleBacklog({
    blocks: [overdueReview, overdueLesson, todayPlannedA, todayPlannedB],
    today,
    dailyLimitByDate: capacityMap,
    backlogQuotaRatio: 0.35,
    lookaheadDays: 2,
  });

  assert.ok(result.movedCount > 0, 'should move at least one backlog block');
  assert.ok(result.insertedTodayCount >= 1, 'should insert backlog into today');

  const todayBlocks = result.blocks
    .filter((block) => toDateKey(new Date(block.date)) === toDateKey(today))
    .sort((a, b) => a.startTime.localeCompare(b.startTime));
  assert.ok(todayBlocks.length > 0, 'today should still have blocks');
  assert.strictEqual(todayBlocks[0].id, 'overdue-review', 'overdue review should be inserted first');

  const todayBacklogMinutes = todayBlocks
    .filter((block) => block.status === 'rescheduled')
    .filter((block) => {
      const original = block.originalDate ? toDateKey(new Date(block.originalDate)) : toDateKey(new Date(block.date));
      return original < toDateKey(today);
    })
    .reduce((sum, block) => sum + block.durationMinutes, 0);
  assert.ok(todayBacklogMinutes <= Math.floor(capacityMap[toDateKey(today)] * 0.4), 'should respect daily backlog quota');

  const uniqueIds = new Set(result.blocks.map((block) => block.id));
  assert.strictEqual(uniqueIds.size, result.blocks.length, 'should not duplicate block ids');
})();

(() => {
  const today = new Date('2026-03-09T00:00:00');
  const tomorrow = new Date('2026-03-10T00:00:00');
  const heavy = makeSubject('recovery', 10, 9, 5);

  const stuck = makeBlock({
    id: 'stuck',
    date: new Date('2026-03-06T00:00:00'),
    startTime: '09:00',
    durationMinutes: 120,
    subject: heavy,
    status: 'rescheduled',
    type: 'AULA',
    rescheduleCount: 4,
  });

  const result = autoRescheduleBacklog({
    blocks: [stuck],
    today,
    dailyLimitByDate: {
      [toDateKey(today)]: 120,
      [toDateKey(tomorrow)]: 120,
    },
    backlogQuotaRatio: 0.35,
    lookaheadDays: 2,
  });

  const recoveryParts = result.blocks.filter((block) => block.description?.includes('Recuperacao'));
  assert.ok(recoveryParts.length >= 2, 'recovery mode should split stuck block into micro-blocks');
  assert.ok(recoveryParts.every((block) => block.durationMinutes <= 40), 'micro-blocks should be shorter');
  assert.ok(result.suggestion.shouldSuggestRecoveryMode, 'should suggest recovery mode when splitting backlog');

  const uniqueIds = new Set(result.blocks.map((block) => block.id));
  assert.strictEqual(uniqueIds.size, result.blocks.length, 'split blocks must keep unique ids');
})();

console.log('backlog rescheduler tests passed');

// ============================================================================
// Regras ditadas pelo usuário (Fase 4) — verificadas uma a uma
// ============================================================================

(() => {
  // 1) "Pular" tira o bloco de hoje, mas o conteúdo reaparece num dia FUTURO.
  //    Se voltasse para hoje, apertar Pular não aliviaria nada.
  const today = new Date();
  today.setHours(0, 0, 0, 0);
  const todayKey = toDateKey(today);
  const subj = makeSubject('pulo', 8, 6, 4);
  const roomy: Record<string, number> = {};
  for (let index = 0; index < 10; index += 1) {
    const day = new Date(today);
    day.setDate(today.getDate() + index);
    roomy[toDateKey(day)] = 360;
  }

  const skippedToday = makeBlock({
    id: 'pulado-hoje',
    date: today,
    startTime: '09:00',
    durationMinutes: 60,
    subject: subj,
    status: 'skipped',
  });

  const result = autoRescheduleBacklog({
    blocks: [skippedToday],
    today,
    dailyLimitByDate: roomy,
    backlogQuotaRatio: 0.35,
    lookaheadDays: 10,
  });

  assert.ok(result.movedCount > 0, 'bloco pulado deve ser reagendado');
  const moved = result.blocks.find((block) => block.id === 'pulado-hoje');
  assert.ok(moved, 'bloco pulado continua existindo');
  assert.ok(toDateKey(new Date(moved!.date)) > todayKey,
    'bloco pulado NAO pode voltar para o mesmo dia');
  assert.notStrictEqual(moved!.status, 'skipped', 'bloco reagendado sai do estado pulado');
})();

(() => {
  // 2) Nada se perde e nada duplica quando há atraso de verdade.
  const today = new Date();
  today.setHours(0, 0, 0, 0);
  const subj = makeSubject('perda', 7, 5, 3);

  const mk = (id: string, daysAgo: number, status: StudyBlock['status'], minutes = 60) => {
    const date = new Date(today);
    date.setDate(today.getDate() - daysAgo);
    return makeBlock({ id, date, startTime: '09:00', durationMinutes: minutes, subject: subj, status });
  };

  const before = [
    mk('atrasado-1', 2, 'scheduled'),
    mk('atrasado-2', 1, 'scheduled', 90),
    mk('concluido', 3, 'completed'),
    mk('pulado', 4, 'skipped', 30),
  ];
  const totalMinutesBefore = before.reduce((sum, block) => sum + block.durationMinutes, 0);

  const result = autoRescheduleBacklog({
    blocks: before,
    today,
    dailyLimitByDate: Object.fromEntries(
      Array.from({ length: 10 }, (_, index) => {
        const day = new Date(today);
        day.setDate(today.getDate() + index);
        return [toDateKey(day), 360];
      })
    ),
    lookaheadDays: 10,
  });

  const ids = new Set(result.blocks.map((block) => block.id));
  assert.strictEqual(result.blocks.length, before.length, 'nenhum bloco pode desaparecer');
  assert.strictEqual(ids.size, result.blocks.length, 'nenhum bloco pode duplicar');
  const totalMinutesAfter = result.blocks
    .filter((block) => !block.isBreak)
    .reduce((sum, block) => sum + block.durationMinutes, 0);
  assert.ok(totalMinutesAfter >= totalMinutesBefore,
    `minutos preservados (${totalMinutesBefore} -> ${totalMinutesAfter})`);

  // 3) Concluído é intocável: o histórico não se reescreve.
  const done = result.blocks.find((block) => block.id === 'concluido')!;
  const doneBefore = before.find((block) => block.id === 'concluido')!;
  assert.strictEqual(toDateKey(new Date(done.date)), toDateKey(new Date(doneBefore.date)),
    'bloco concluido nao muda de dia');
  assert.strictEqual(done.status, 'completed', 'bloco concluido continua concluido');

  // 4) Atrasado sai do passado (ou é relatado como pendente, nunca some em silencio).
  const overdue = result.blocks.filter((block) => block.id.startsWith('atrasado'));
  const stillPast = overdue.filter((block) => toDateKey(new Date(block.date)) < toDateKey(today));
  assert.ok(overdue.length === 2 && stillPast.length === 0,
    'com folga, todo atrasado sai do passado');

  // 5) Idempotente: rodar de novo não muda mais nada.
  const second = autoRescheduleBacklog({
    blocks: result.blocks,
    today,
    dailyLimitByDate: Object.fromEntries(
      Array.from({ length: 10 }, (_, index) => {
        const day = new Date(today);
        day.setDate(today.getDate() + index);
        return [toDateKey(day), 360];
      })
    ),
    lookaheadDays: 10,
  });
  assert.strictEqual(second.movedCount, 0, 'segunda passada nao move nada');
  assert.strictEqual(second.blocks.length, result.blocks.length, 'segunda passada nao perde blocos');
})();

(() => {
  // 6) Só remarca para os dias em que o usuário estuda.
  const today = new Date();
  today.setHours(0, 0, 0, 0);
  const subj = makeSubject('fds', 6, 5, 3);
  const date = new Date(today);
  date.setDate(today.getDate() - 2);

  const result = autoRescheduleBacklog({
    blocks: [makeBlock({ id: 'atrasado-fds', date, startTime: '09:00', durationMinutes: 60, subject: subj })],
    today,
    allowedDays: [0, 6],
    dailyLimitByDate: Object.fromEntries(
      Array.from({ length: 10 }, (_, index) => {
        const day = new Date(today);
        day.setDate(today.getDate() + index);
        return [toDateKey(day), 360];
      })
    ),
    lookaheadDays: 10,
  });

  const moved = result.blocks.find((block) => block.id === 'atrasado-fds')!;
  const weekday = new Date(moved.date).getDay();
  assert.ok(result.movedCount > 0 && (weekday === 0 || weekday === 6),
    `so remarca para dias permitidos (caiu no dia ${weekday})`);
})();

(() => {
  // 7) Quem quiser tratar "pulado" como descarte pode pedir explicitamente.
  const today = new Date();
  today.setHours(0, 0, 0, 0);
  const subj = makeSubject('descarte', 6, 5, 3);

  const result = autoRescheduleBacklog({
    blocks: [
      makeBlock({
        id: 'pulado-descartado',
        date: today,
        startTime: '09:00',
        durationMinutes: 60,
        subject: subj,
        status: 'skipped',
      }),
    ],
    today,
    dailyLimitByDate: Object.fromEntries(
      Array.from({ length: 6 }, (_, index) => {
        const day = new Date(today);
        day.setDate(today.getDate() + index);
        return [toDateKey(day), 360];
      })
    ),
    lookaheadDays: 6,
    rescheduleSkipped: false,
  });

  assert.strictEqual(result.movedCount, 0, 'com rescheduleSkipped:false, pulado nao é reagendado');
  assert.strictEqual(result.blocks.length, 1, 'e o bloco continua existindo no histórico');
})();

// ============================================================================
// Trava sequencial (#6e)
// ============================================================================
import { checkSequentialLock } from '../src/services/sequentialLock';

(() => {
  const today = new Date();
  today.setHours(0, 0, 0, 0);
  const subj = makeSubject('trava', 7, 5, 3);
  const day = (offset: number) => {
    const date = new Date(today);
    date.setDate(today.getDate() + offset);
    return date;
  };

  const todayPending = makeBlock({
    id: 'hoje-pendente', date: day(0), startTime: '09:00', durationMinutes: 60, subject: subj,
  });
  const futureBlock = makeBlock({
    id: 'amanha', date: day(1), startTime: '09:00', durationMinutes: 60, subject: subj,
  });

  // 1) Com hoje pendente, bloco de amanhã está travado.
  const locked = checkSequentialLock(futureBlock, [todayPending, futureBlock], today);
  assert.strictEqual(locked.allowed, false, 'bloco de dia futuro deve travar com hoje pendente');
  assert.ok(locked.pendingToday >= 1, 'deve informar quantos blocos de hoje estão pendentes');
  assert.ok(locked.message.includes('hoje'), 'mensagem deve mencionar o dia de hoje');

  // 2) Sem pendência hoje, libera.
  const done = { ...todayPending, status: 'completed' as const };
  const free = checkSequentialLock(futureBlock, [done, futureBlock], today);
  assert.strictEqual(free.allowed, true, 'sem pendência hoje, o dia futuro libera');

  // 3) Pulado não bloqueia (saiu da fila por decisão do usuário).
  const skipped = { ...todayPending, status: 'skipped' as const };
  const afterSkip = checkSequentialLock(futureBlock, [skipped, futureBlock], today);
  assert.strictEqual(afterSkip.allowed, true, 'bloco pulado não deve travar o dia seguinte');

  // 4) O próprio bloco de hoje nunca é travado pela regra.
  const todayOk = checkSequentialLock(todayPending, [todayPending, futureBlock], today);
  assert.strictEqual(todayOk.allowed, true, 'bloco de hoje pode ser iniciado');

  // 5) Bloco atrasado (dia passado) também pode — é justamente o que precisa resolver.
  const overdue = makeBlock({
    id: 'atrasado', date: day(-2), startTime: '09:00', durationMinutes: 60, subject: subj,
  });
  const overdueOk = checkSequentialLock(overdue, [overdue, todayPending, futureBlock], today);
  assert.strictEqual(overdueOk.allowed, true, 'bloco atrasado pode ser iniciado');
})();
