/**
 * Testes do diagnóstico de espaço para reagendar (#21).
 * Rodar: npm run test:capacity
 */
import { analyzeBacklogCapacity, formatMinutesAsHours } from '../src/services/backlogCapacity';
import { autoRescheduleBacklog } from '../src/services/backlogRescheduler';
import type { StudyBlock } from '@/src/types';

let falhas = 0;
const check = (nome: string, ok: boolean, extra = '') => {
  console.log(`${ok ? '✔' : '✘'} ${nome}${ok ? '' : ` — ${extra}`}`);
  if (!ok) falhas++;
};

const HOJE = new Date(2026, 8, 28); // 28/09/2026 (segunda)
const key = (d: Date) =>
  `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`;
const dia = (offset: number) => {
  const d = new Date(HOJE);
  d.setDate(HOJE.getDate() + offset);
  return key(d);
};

const bloco = (
  id: string,
  dateKey: string,
  minutos: number,
  extra: Partial<StudyBlock> = {}
): StudyBlock =>
  ({
    id,
    userId: 'local',
    subjectId: 'mat',
    date: new Date(`${dateKey}T09:00:00`),
    startTime: '09:00',
    endTime: '10:00',
    durationMinutes: minutos,
    status: 'scheduled',
    isBreak: false,
    isAutoGenerated: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    ...extra,
  }) as StudyBlock;

const segSex = [1, 2, 3, 4, 5];
/** Os dias da janela (seg–sex) dentro de `lookaheadDays` a partir de hoje. */
const diasJanela = Array.from({ length: 11 }, (_, i) => dia(i)).filter((k) => {
  const [y, m, d] = k.split('-').map(Number);
  return segSex.includes(new Date(y, m - 1, d).getDay());
});
const DIAS = diasJanela.length;

// 1. Sem limite e sem blocos, o dia não tem capacidade (comportamento antigo).
const r1 = analyzeBacklogCapacity({ blocks: [], today: HOJE, allowedDays: segSex });
check('sem limite e sem blocos: zero espaço', r1.usableMinutes === 0 && r1.noSpace, JSON.stringify(r1));

// 2. Com o fallback por dia da semana, dias fora do cronograma têm capacidade.
const r2 = analyzeBacklogCapacity({
  blocks: [],
  today: HOJE,
  allowedDays: segSex,
  fallbackDayMinutesByWeekday: { 1: 240, 2: 240, 3: 240, 4: 240, 5: 240 },
});
check(`fallback: ${DIAS} dias × 240 min, cotados a 84 min/dia`, r2.usableMinutes === DIAS * 84, String(r2.usableMinutes));
check(`fallback: ${DIAS} dias com espaço`, r2.daysWithSpace === DIAS, String(r2.daysWithSpace));

// 3. Dias cheios: todos os dias da janela com o limite já usado → nenhum espaço.
const cheios = diasJanela.map((k, i) => bloco(`c${i}`, k, 240));
const limites: Record<string, number> = {};
diasJanela.forEach((k) => {
  limites[k] = 240;
});
const r3 = analyzeBacklogCapacity({
  blocks: cheios,
  today: HOJE,
  allowedDays: segSex,
  dailyLimitByDate: limites,
});
check('dias cheios: nenhum espaço', r3.noSpace && r3.usableMinutes === 0, JSON.stringify(r3));

// 4. Pendências que não cabem: calcula quantos minutos extras por dia faltam.
const pendentes = [bloco('p1', dia(-3), 50), bloco('p2', dia(-2), 50), bloco('p3', dia(-1), 50)];
const r4 = analyzeBacklogCapacity({
  blocks: [...cheios, ...pendentes],
  today: HOJE,
  allowedDays: segSex,
  dailyLimitByDate: limites,
});
check('pendências contadas', r4.pendingCount === 3, String(r4.pendingCount));
check('pendências somam 150 min', r4.pendingMinutes === 150, String(r4.pendingMinutes));
check('faltam 150 min', r4.missingMinutes === 150, String(r4.missingMinutes));
check(`sugere 17 min extras por dia (150 ÷ ${DIAS})`, r4.extraMinutesPerDay === Math.ceil(150 / DIAS), String(r4.extraMinutesPerDay));

// 5. Quando cabe, não sugere nada extra.
const r5 = analyzeBacklogCapacity({
  blocks: [...pendentes],
  today: HOJE,
  allowedDays: segSex,
  fallbackDayMinutesByWeekday: { 1: 240, 2: 240, 3: 240, 4: 240, 5: 240 },
});
check('quando cabe: nada falta', r5.missingMinutes === 0 && r5.extraMinutesPerDay === 0, JSON.stringify(r5));
check('quando cabe: não marca "sem espaço"', !r5.noSpace);

// 6. O motor usa o fallback: cronograma gerado e cheio até 01/10; os dias
//    seguintes não têm limite nem blocos, e o fallback dá capacidade a eles.
const diasGerados = diasJanela.slice(0, 4);
const ateFim = diasGerados.map((k, i) => bloco(`f${i}`, k, 240));
const limitesCheios: Record<string, number> = {};
diasGerados.forEach((k) => {
  limitesCheios[k] = 240;
});
const antes = autoRescheduleBacklog({
  blocks: [...ateFim, bloco('atrasado', dia(-2), 50)],
  today: HOJE,
  allowedDays: segSex,
  dailyLimitByDate: limitesCheios,
});
check('motor sem fallback: dias cheios não movem nada', antes.movedCount === 0, String(antes.movedCount));

const depois = autoRescheduleBacklog({
  blocks: [...ateFim, bloco('atrasado', dia(-2), 50)],
  today: HOJE,
  allowedDays: segSex,
  dailyLimitByDate: limitesCheios,
  fallbackDayMinutesByWeekday: { 1: 240, 2: 240, 3: 240, 4: 240, 5: 240, 6: 240, 0: 240 },
});
check('motor com fallback: dias livres além do limite aceitam o bloco', depois.movedCount > 0, String(depois.movedCount));
check('motor com fallback: nada é perdido', depois.pendingBacklogCount < 1, String(depois.pendingBacklogCount));

// 7. Formatação de horas (nunca decimal cru).
check('150 min = 2h30', formatMinutesAsHours(150) === '2:30', formatMinutesAsHours(150));
check('90 min = 1h30', formatMinutesAsHours(90) === '1:30', formatMinutesAsHours(90));

console.log(falhas === 0 ? '\nTodos os casos passaram.' : `\n${falhas} caso(s) falharam.`);
process.exit(falhas === 0 ? 0 : 1);
