import assert from 'node:assert';
import { planBlockMove } from '../src/services/blockMove';
import type { StudyBlock, Subject } from '../src/types';

/**
 * Testes da movimentação de blocos (#13).
 *
 * Regras verificadas:
 *  1. "Adicionar matéria avulsa" REALOCA o bloco existente — nunca cria outro
 *     da mesma matéria (não duplica);
 *  2. "Adiantar" só puxa bloco de dia posterior ao alvo;
 *  3. o bloco mantém duração, matéria e tipo; muda o dia e o horário;
 *  4. encaixa sem colidir, sempre com intervalo entre blocos;
 *  5. quando não há bloco elegível, explica o motivo em vez de falhar calado.
 */

const toDateKey = (date: Date) =>
  `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(
    date.getDate()
  ).padStart(2, '0')}`;

const subject: Subject = {
  id: 'mat',
  userId: 'user-1',
  name: 'Matemática',
  color: '#00B4FF',
  icon: 'book',
  area: 'geral',
  priority: 8,
  difficulty: 6,
  pesoNoExame: 5,
  targetHours: 10,
  completedHours: 0,
  totalHours: 0,
  sessionsCount: 0,
  averageScore: 0,
  isActive: true,
  createdAt: new Date('2026-01-01T00:00:00'),
  updatedAt: new Date('2026-01-01T00:00:00'),
};

const otherSubject: Subject = { ...subject, id: 'outra', name: 'História' };

const block = (params: {
  id: string;
  date: string;
  startTime: string;
  durationMinutes: number;
  subjectId?: string;
  status?: StudyBlock['status'];
  type?: StudyBlock['type'];
}): StudyBlock => ({
  id: params.id,
  userId: 'user-1',
  subjectId: params.subjectId ?? 'mat',
  date: new Date(`${params.date}T00:00:00`),
  startTime: params.startTime,
  endTime: '10:00',
  durationMinutes: params.durationMinutes,
  status: params.status ?? 'scheduled',
  isBreak: false,
  isAutoGenerated: true,
  type: params.type ?? 'AULA',
  createdAt: new Date('2026-01-01T00:00:00'),
  updatedAt: new Date('2026-01-01T00:00:00'),
});

const TODAY = new Date('2026-09-28T00:00:00');

(() => {
  const blocks = [
    block({ id: 'hoje', date: '2026-09-28', startTime: '08:00', durationMinutes: 60 }),
    block({ id: 'amanha', date: '2026-09-29', startTime: '09:00', durationMinutes: 60 }),
    block({ id: 'depois', date: '2026-09-30', startTime: '09:00', durationMinutes: 60, subjectId: 'outra' }),
  ];

  const result = planBlockMove({
    blocks,
    subjects: [subject, otherSubject],
    subjectId: 'mat',
    targetDate: TODAY,
    mode: 'adiantar',
    preferredStart: '19:00',
    breakMinutes: 15,
  });

  assert.ok(result.ok, 'adiantar deve funcionar quando existe bloco em dia posterior');
  assert.strictEqual(result.movedBlockId, 'amanha', 'deve puxar o bloco do dia seguinte');
  assert.strictEqual(result.fromDateKey, '2026-09-29');
  assert.strictEqual(result.toDateKey, '2026-09-28');

  // Não duplica: a quantidade de blocos é a mesma e os ids continuam únicos.
  assert.strictEqual(result.blocks?.length, blocks.length, 'nao pode criar bloco novo');
  const unique = new Set(result.blocks?.map((item) => item.id));
  assert.strictEqual(unique.size, result.blocks?.length, 'nao pode duplicar ids');

  // O bloco movido mantém duração e matéria, e muda o dia.
  const moved = result.blocks?.find((item) => item.id === 'amanha')!;
  assert.strictEqual(moved.durationMinutes, 60, 'duração preservada');
  assert.strictEqual(moved.subjectId, 'mat', 'matéria preservada');
  assert.strictEqual(toDateKey(new Date(moved.date)), '2026-09-28', 'mudou para o dia alvo');
  assert.strictEqual(moved.status, 'rescheduled', 'bloco movido fica como remarcado');
  assert.ok(moved.originalDate, 'guarda a data original');

  // O bloco do outro dia que não foi movido continua intacto.
  const untouched = result.blocks?.find((item) => item.id === 'depois')!;
  assert.strictEqual(toDateKey(new Date(untouched.date)), '2026-09-30', 'bloco de outra matéria intacto');
})();

(() => {
  // Realocar também move (não cria) e respeita o horário pedido.
  const blocks = [
    block({ id: 'hoje', date: '2026-09-28', startTime: '08:00', durationMinutes: 60 }),
    block({ id: 'amanha', date: '2026-09-29', startTime: '09:00', durationMinutes: 90 }),
  ];

  const result = planBlockMove({
    blocks,
    subjects: [subject],
    subjectId: 'mat',
    targetDate: TODAY,
    mode: 'realocar',
    preferredStart: '19:00',
    breakMinutes: 15,
  });

  assert.ok(result.ok);
  assert.strictEqual(result.movedBlockId, 'amanha');
  assert.strictEqual(result.placedStart, '19:00', 'respeita o horário escolhido');
  assert.strictEqual(result.placedEnd, '20:30', 'mantém a duração de 90 min');
  assert.strictEqual(result.blocks?.length, 2, 'continua com 2 blocos');
})();

(() => {
  // Colisão: encaixa depois do bloco existente + intervalo.
  const blocks = [
    block({ id: 'alvo', date: '2026-09-28', startTime: '09:00', durationMinutes: 60 }),
    block({ id: 'futuro', date: '2026-09-29', startTime: '09:00', durationMinutes: 60 }),
  ];

  const result = planBlockMove({
    blocks,
    subjects: [subject],
    subjectId: 'mat',
    targetDate: TODAY,
    mode: 'realocar',
    preferredStart: '09:30', // colide com o bloco das 09:00-10:00
    breakMinutes: 15,
  });

  assert.ok(result.ok);
  assert.strictEqual(result.placedStart, '10:15', 'empurra para depois do bloco + intervalo');
  assert.strictEqual(result.placedEnd, '11:15');
})();

(() => {
  // Adiantar sem bloco depois do alvo: explica em vez de falhar calado.
  const blocks = [
    block({ id: 'hoje', date: '2026-09-28', startTime: '08:00', durationMinutes: 60 }),
    block({ id: 'ontem', date: '2026-09-27', startTime: '08:00', durationMinutes: 60 }),
  ];

  const result = planBlockMove({
    blocks,
    subjects: [subject],
    subjectId: 'mat',
    targetDate: TODAY,
    mode: 'adiantar',
    preferredStart: '19:00',
  });

  assert.strictEqual(result.ok, false, 'não deve mover quando não há bloco posterior');
  assert.ok(result.reason?.includes('depois'), 'explica o motivo');
  assert.strictEqual(result.blocks, undefined, 'não devolve lista alterada');
})();

(() => {
  // Bloco concluído ou pulado não é movido.
  const blocks = [
    block({ id: 'feito', date: '2026-09-29', startTime: '09:00', durationMinutes: 60, status: 'completed' }),
    block({ id: 'pulado', date: '2026-09-30', startTime: '09:00', durationMinutes: 60, status: 'skipped' }),
  ];

  const result = planBlockMove({
    blocks,
    subjects: [subject],
    subjectId: 'mat',
    targetDate: TODAY,
    mode: 'adiantar',
    preferredStart: '19:00',
  });

  assert.strictEqual(result.ok, false, 'concluído/pulado não podem ser movidos');
  assert.strictEqual(result.blocks, undefined);
})();

console.log('\nblock move tests passed');
