import assert from 'node:assert';
import { computeGamificationSnapshot, computeStudyStreak } from '../src/lib/progressSnapshot';
import { getEnemPresetSubjects } from '../src/lib/enemCatalog';
import { applyBlockCompletionMetrics } from '../src/services/adaptiveStudyIntelligence';
import { generateWeeklySchedule } from '../src/services/studyAlgorithm';
import type { AnalyticsStore, StudyBlock, Subject } from '../src/types';

function makeSubject(partial: Partial<Subject> = {}): Subject {
  const now = new Date();
  return {
    id: 'matematica',
    userId: 'user1',
    name: 'Matemática',
    color: '#00B4FF',
    icon: 'book',
    priority: 8,
    difficulty: 5,
    targetHours: 7,
    completedHours: 0,
    totalHours: 0,
    sessionsCount: 0,
    averageScore: 0,
    isActive: true,
    createdAt: now,
    updatedAt: now,
    ...partial,
  };
}

function makeCompletedBlock(partial: Partial<StudyBlock> = {}): StudyBlock {
  const now = new Date(2026, 4, 15, 10, 0, 0);
  const subject = makeSubject();
  return {
    id: 'block-1',
    userId: 'user1',
    subjectId: subject.id,
    subject,
    date: now,
    startTime: '08:00',
    endTime: '10:00',
    durationMinutes: 120,
    status: 'completed',
    isBreak: false,
    isAutoGenerated: true,
    originalDate: now,
    completedAt: now,
    rescheduleCount: 0,
    createdAt: now,
    updatedAt: now,
    ...partial,
  };
}

const now = new Date(2026, 4, 15, 10, 0, 0);
const yesterdayAndBefore: AnalyticsStore['daily'] = {
  '2026-05-13': { hours: 1, sessions: 1 },
  '2026-05-14': { hours: 1.5, sessions: 1 },
};

assert.strictEqual(
  computeStudyStreak(yesterdayAndBefore, {}, now),
  2,
  'streak should stay active in the morning when the student studied yesterday'
);

assert.strictEqual(
  computeStudyStreak({ ...yesterdayAndBefore, '2026-05-15': { hours: 0.5, sessions: 1 } }, {}, now),
  3,
  'streak should include today after the student studies'
);

assert.strictEqual(
  computeStudyStreak({ '2026-05-13': { hours: 2, sessions: 1 } }, {}, now),
  0,
  'streak should reset only after yesterday was missed'
);

const emptyGamification = computeGamificationSnapshot({
  plannerBlocks: [],
  analytics: { daily: {} },
  now,
});
assert.strictEqual(emptyGamification.level, 1, 'new students should start at level 1');
assert.strictEqual(emptyGamification.totalXp, 0, 'new students should start with 0 XP');

const studiedGamification = computeGamificationSnapshot({
  plannerBlocks: [makeCompletedBlock()],
  analytics: { daily: {} },
  now,
});
assert.strictEqual(studiedGamification.totalXp, 120, 'completed study minutes should become XP');
assert.strictEqual(studiedGamification.level, 2, '120 XP should place the student at level 2');

const exerciseMetrics = applyBlockCompletionMetrics({
  analytics: { daily: {} },
  block: makeCompletedBlock({ type: 'EXERCICIOS', sessionType: 'pratica', durationMinutes: 60 }),
  subject: makeSubject(),
  minutesSpent: 60,
  correctAnswers: 8,
  totalQuestions: 10,
  now,
});
assert.strictEqual(
  exerciseMetrics.snapshot?.accuracyRate,
  0.8,
  'exercise completion with answers should use real accuracy instead of an estimate'
);
assert.strictEqual(exerciseMetrics.snapshot?.correctAnswers, 8, 'real correct answers should be stored');
assert.strictEqual(exerciseMetrics.snapshot?.totalQuestions, 10, 'real question totals should be stored');

const weekStart = new Date(2026, 4, 11);
const weekEnd = new Date(2026, 4, 17);
const weeklySchedule = generateWeeklySchedule({
  userId: 'user1',
  subjects: [makeSubject({ targetHours: 7, difficulty: 5 })],
  preferredStart: '08:00',
  preferredEnd: '20:00',
  maxBlockMinutes: 120,
  breakMinutes: 10,
  excludeDays: [0],
  startDate: weekStart,
  endDate: weekEnd,
});

assert.ok(
  Math.abs(weeklySchedule.totalHours - 7) < 0.001,
  `weekly target should be compressed into active days, got ${weeklySchedule.totalHours}h`
);
assert.ok(
  weeklySchedule.blocks.filter((block) => !block.isBreak).every((block) => block.date.getDay() !== 0),
  'weekly schedule should not create study blocks on excluded Sundays'
);

const enemPresetGroups = new Set(getEnemPresetSubjects().map((subject) => subject.group));
assert.deepStrictEqual(
  Array.from(enemPresetGroups).sort(),
  ['Humanas', 'Linguagens', 'Matemática', 'Natureza'].sort(),
  'ENEM preset preview should be grouped by official exam areas instead of Outros'
);

console.log('student product audit tests passed');
