#!/usr/bin/env node
/**
 * Teste do motor de recálculo (Fase 4, itens #6c/#6d/#13a).
 *
 *   npx tsx scripts/test-backlog-rescheduler.mts
 *
 * Roda direto na função pura `autoRescheduleBacklog` (sem servidor). Garante:
 *   1. bloco não cumprido de dia passado é empurrado para um dia futuro;
 *   2. concluído e pulado NUNCA são alterados (histórico não se reescreve);
 *   3. nenhum bloco desaparece e nenhum é duplicado (#13a: "avulsa" não pode
 *      criar matéria repetida);
 *   4. os minutos de estudo são preservados (nada de hora sumindo);
 *   5. o que não cabe na quota continua na lista e é relatado — nunca some em
 *      silêncio;
 *   6. rodar duas vezes não faz nova mudança (idempotente);
 *   7. pausas (isBreak) são mantidas e os dias permitidos são respeitados.
 */

// tsx carrega os .ts como CommonJS (o package.json não tem "type": "module"),
// então as funções chegam pelo export padrão.
import backlogModule from '../src/services/backlogRescheduler';
import type { StudyBlock } from '../src/types';

const { autoRescheduleBacklog } = backlogModule as unknown as {
  autoRescheduleBacklog: (config: Record<string, unknown>) => {
    blocks: StudyBlock[];
    movedCount: number;
    backlogBefore: number;
    backlogAfter: number;
    pendingBacklogCount: number;
    changedBlockIds: string[];
  };
};

let passed = 0;
let failed = 0;
const failures: string[] = [];

const check = (label: string, condition: boolean, detail = '') => {
  if (condition) {
    passed += 1;
    console.log(`  ✔ ${label}${detail ? ` — ${detail}` : ''}`);
  } else {
    failed += 1;
    failures.push(`${label}${detail ? ` — ${detail}` : ''}`);
    console.log(`  ✘ ${label}${detail ? ` — ${detail}` : ''}`);
  }
};

const localKey = (date: Date) => {
  const month = String(date.getMonth() + 1).padStart(2, '0');
  const day = String(date.getDate()).padStart(2, '0');
  return `${date.getFullYear()}-${month}-${day}`;
};

const block = (over: Partial<StudyBlock> & { id: string; daysFromToday: number }): StudyBlock => {
  const date = new Date();
  date.setHours(0, 0, 0, 0);
  date.setDate(date.getDate() + over.daysFromToday);
  return {
    id: over.id,
    userId: 'local',
    subjectId: over.subjectId ?? 'mat',
    date,
    startTime: over.startTime ?? '09:00',
    endTime: over.endTime ?? '10:00',
    durationMinutes: over.durationMinutes ?? 60,
    status: over.status ?? 'scheduled',
    isBreak: over.isBreak ?? false,
    isAutoGenerated: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  };
};

const todayKey = localKey(new Date());
const studyMinutes = (blocks: StudyBlock[]) =>
  blocks.filter((b) => !b.isBreak).reduce((sum, b) => sum + b.durationMinutes, 0);
const ids = (blocks: StudyBlock[]) => new Set(blocks.map((b) => b.id));

/** Limite folgado (6h/dia) para os próximos 12 dias. */
const roomyLimits = () =>
  Object.fromEntries(
    Array.from({ length: 12 }, (_, index) => {
      const date = new Date();
      date.setHours(0, 0, 0, 0);
      date.setDate(date.getDate() + index);
      return [localKey(date), 360];
    })
  );

// ---------------------------------------------------------------- cenário base
const base: StudyBlock[] = [
  block({ id: 'atrasado-1', daysFromToday: -2 }),
  block({ id: 'atrasado-2', daysFromToday: -1, startTime: '09:00', endTime: '10:30', durationMinutes: 90 }),
  block({ id: 'hoje-feito', daysFromToday: 0, status: 'completed', startTime: '08:00', endTime: '09:00' }),
  block({ id: 'amanha', daysFromToday: 1 }),
  block({ id: 'pulado', daysFromToday: -3, status: 'skipped', startTime: '09:00', endTime: '09:30', durationMinutes: 30 }),
  block({ id: 'pausa', daysFromToday: 0, isBreak: true, startTime: '10:00', endTime: '10:15', durationMinutes: 15 }),
];

console.log('\n── Motor de recálculo (Fase 4) — cenário com pouca folga');
const result = autoRescheduleBacklog({
  blocks: base,
  today: new Date(),
  allowedDays: [0, 1, 2, 3, 4, 5, 6],
  breakMinutes: 15,
});

check('nenhum bloco desaparece', result.blocks.length === base.length,
  `${result.blocks.length} de ${base.length}`);
check('nenhum bloco duplicado', ids(result.blocks).size === result.blocks.length,
  `${ids(result.blocks).size} ids únicos`);
check('minutos de estudo preservados', studyMinutes(result.blocks) === studyMinutes(base),
  `${studyMinutes(base)} → ${studyMinutes(result.blocks)} min`);

const byId = new Map(result.blocks.map((b) => [b.id, b]));
const sameAs = (id: string, source: StudyBlock[] = base) => {
  const before = source.find((b) => b.id === id)!;
  const after = byId.get(id)!;
  return (
    localKey(new Date(after.date)) === localKey(new Date(before.date)) &&
    after.startTime === before.startTime &&
    after.endTime === before.endTime &&
    after.status === before.status &&
    after.durationMinutes === before.durationMinutes &&
    after.isBreak === before.isBreak
  );
};

check('bloco concluído nunca é alterado', sameAs('hoje-feito'));
check('bloco pulado nunca é alterado', sameAs('pulado'));
check('pausa continua sendo pausa', byId.get('pausa')?.isBreak === true && sameAs('pausa'));

// Nada pode ficar "esquecido": ou foi remarcado para hoje/diante, ou continua
// na lista e entra no relatório de pendências.
const accountedFor = ['atrasado-1', 'atrasado-2'].every((id) => {
  const after = byId.get(id)!;
  const movedForward = localKey(new Date(after.date)) >= todayKey;
  return movedForward || result.pendingBacklogCount > 0;
});
check('atrasado é remarcado ou relatado como pendente', accountedFor,
  `movedCount=${result.movedCount}, pendentes=${result.pendingBacklogCount}`);

// ---------------------------------------------------------------- com folga
console.log('\n── Cenário com folga (limite alto por dia)');
const roomy = autoRescheduleBacklog({
  blocks: base,
  today: new Date(),
  allowedDays: [0, 1, 2, 3, 4, 5, 6],
  breakMinutes: 15,
  dailyLimitByDate: roomyLimits(),
});

const roomyById = new Map(roomy.blocks.map((b) => [b.id, b]));
const allOverdueMoved = ['atrasado-1', 'atrasado-2'].every(
  (id) => localKey(new Date(roomyById.get(id)!.date)) >= todayKey
);
check('com folga, todo atrasado sai do passado', allOverdueMoved,
  `movedCount=${roomy.movedCount}`);
check('com folga, nada fica pendente', roomy.pendingBacklogCount === 0,
  `pendentes=${roomy.pendingBacklogCount}`);
check('com folga, blocos preservados', roomy.blocks.length === base.length);
check('com folga, minutos preservados', studyMinutes(roomy.blocks) === studyMinutes(base));
check('com folga, pulado continua intacto',
  localKey(new Date(roomyById.get('pulado')!.date)) === localKey(new Date(base[4].date)) &&
  roomyById.get('pulado')!.status === 'skipped');

// ---------------------------------------------------------------- idempotência
console.log('\n── Idempotência');
const second = autoRescheduleBacklog({
  blocks: result.blocks,
  today: new Date(),
  allowedDays: [0, 1, 2, 3, 4, 5, 6],
  breakMinutes: 15,
});
check('segunda passada não move nada', second.movedCount === 0, `movedCount=${second.movedCount}`);
check('segunda passada não perde blocos', second.blocks.length === result.blocks.length);

// ---------------------------------------------------------------- sem atraso
console.log('\n── Sem nada atrasado');
const onlyDone: StudyBlock[] = [
  block({ id: 'feito-1', daysFromToday: -2, status: 'completed' }),
  block({ id: 'hoje', daysFromToday: 0 }),
  block({ id: 'amanha-2', daysFromToday: 1 }),
];
const noBacklog = autoRescheduleBacklog({
  blocks: onlyDone,
  today: new Date(),
  allowedDays: [0, 1, 2, 3, 4, 5, 6],
});
check('nada atrasado → nada muda', noBacklog.movedCount === 0 && noBacklog.blocks.length === 3);

// ---------------------------------------------------------------- dias permitidos
console.log('\n── Respeito aos dias de estudo');
const weekendOnly = autoRescheduleBacklog({
  blocks: [block({ id: 'atrasado-fds', daysFromToday: -2 })],
  today: new Date(),
  allowedDays: [0, 6],
  breakMinutes: 15,
  dailyLimitByDate: roomyLimits(),
});
const fds = weekendOnly.blocks.find((b) => b.id === 'atrasado-fds');
const fdsDay = fds ? new Date(fds.date).getDay() : -1;
check('só remarca para dias permitidos', weekendOnly.movedCount > 0 && (fdsDay === 0 || fdsDay === 6),
  `caiu no dia ${fdsDay} (0=dom, 6=sáb)`);

console.log(`\n${passed} passaram, ${failed} falharam`);
if (failed > 0) {
  console.log('\nFalhas:');
  failures.forEach((f) => console.log(`  - ${f}`));
  process.exit(1);
}
